apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "database-k8s-operator.fullname" . }}
  labels:
    app: {{ template "database-k8s-operator.name" . }}
    chart: {{ template "database-k8s-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}